version: "3.9"

services:
  generator:
    image: nginx-generator
    container_name: generator
    volumes:
      - .:/workspace:z
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
